### ISSUE TITLE
License

### ISSUE THREAD

**Issue by wing328** [OpenAPITools/openapi-generator-bazel#1]
@mrmeku for the license, what about using Apache v2 (same as OpenAPI-Generator)?

**Comment by mrmeku** [comment]
Sounds good to me! I've added it to the root of the repo. @wing328 Some bazel projects such as rules_nodejs add licence information as a header for every file in the repo. For example: https://github.com/bazelbuild/rules_nodejs/blob/master/defs.bzl#L1

Would you like to follow this convention? Its a bit onerous for contributors, but I'll do whatever direction you think is best.

**Comment by wing328** [comment]
For copyright, let's use the following:

> Copyright 2019 OpenAPI-Generator-Bazel Contributors

Last time, I used an IDE (Intellji) to add a license header for every file in OpenAPI Generator. If you need help adding these license headers, let me know and I'll see if there's an easy way to do so.

cc @jimschubert

**Comment by mrmeku** [comment]
Naw, the project is intentionally only made up of like 10 files. It'll only take me a second to add the header to all files
