### ISSUE TITLE
sha256 in README is wrong.

### ISSUE THREAD

**Issue by PI-Victor** [OpenAPITools/openapi-generator-bazel#20]
```
http_archive(
    name = "openapi_tools_generator_bazel",
    sha256 = "bdec4feb06144a1dc0a6f9955de9f0079a98b7442275bc84a4fd00452437c945",
    urls = ["https://github.com/OpenAPITools/openapi-generator-bazel/releases/download/0.1.5/openapi-tools-generator-bazel-0.1.5.tar.gz"],
)
```

the sha256 for the url specified in the [README.md](https://github.com/OpenAPITools/openapi-generator-bazel#quickstart) is not accurate, adding this to your `WORKSPACE` file will fail.

```
$ wget https://github.com/OpenAPITools/openapi-generator-bazel/releases/download/0.1.5/openapi-tools-generator-bazel-0.1.5.tar.gz
...
$ sha256sum openapi-tools-generator-bazel-0.1.5.tar.gz
c6e4c253f1ae0fbe4d4ded8a719f6647273141d0dc3c0cd8bb074aa7fc3c8d1c  openapi-tools-generator-bazel-0.1.5.tar.gz
```
this was [a mistake in a commit](https://github.com/OpenAPITools/openapi-generator-bazel/commit/64f02f2d0098d0c3704039eb2ab9d908f1b255b4) that only updated the archive URL and not the sha as well.

**Comment by wing328** [comment]
@PI-Victor thanks for reporting the issue. I've fixed it via https://github.com/OpenAPITools/openapi-generator-bazel/commit/f30b7d22381603960b01b92d523b86032f6bf935
