### ISSUE TITLE
No such package '@openapi_tools_generator_bazel_cli//jar'

### ISSUE THREAD

**Issue by colinlmcdonald** [OpenAPITools/openapi-generator-bazel#21]
I'm getting this error when trying to build:

`//external:openapi_tools_generator_bazel/dependency/openapi-generator-cli depends on @openapi_tools_generator_bazel_cli//jar:jar in repository @openapi_tools_generator_bazel_cli which failed to fetch. no such package '@openapi_tools_generator_bazel_cli//jar': java.io.IOException: Error downloading [https://jcenter.bintray.com/org/openapitools/openapi-generator-cli/5.1.0/openapi-generator-cli-5.1.0.jar, https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/5.1.0/openapi-generator-cli-5.1.0.jar] to /private/var/tmp/_bazel_cmcdonald/985a8425008e54c48c1ca7331d5a96e7/external/openapi_tools_generator_bazel_cli/openapi-generator-cli-5.1.0.jar: Checksum was 62f9842f0fcd91e4afeafc33f19a7af41f2927c7472c601310cedfc72ff1bb19 but wanted e4e45d5441283b2f0f4bf988d02186b85425e7b708b4be0b06e3bfd7c7aa52c7`

I'm new to bazel so sorry if I'm missing something obvious, but trying to follow the readme. Thanks!

**Comment by DavisJaunzems** [comment]
In your WORKSPACE update:
```
openapi_tools_generator_bazel_repositories(
    openapi_generator_cli_version = "5.1.0",
    sha256 = "62f9842f0fcd91e4afeafc33f19a7af41f2927c7472c601310cedfc72ff1bb19",
)
```
