### ISSUE TITLE
Failure to run basic example

### ISSUE THREAD

**Issue by uniquefine** [OpenAPITools/openapi-generator-bazel#29]
I tried to execute the getting started example setup. 
The generation target fails because the checksum of the downloaded cli file is different from the code. 
The minimum setup to reproduce the error is attached. 
[reproduce_failure.zip](https://github.com/OpenAPITools/openapi-generator-bazel/files/7648815/reproduce_failure.zip)

**Comment by oncilla** [comment]
@uniquefine I think this is resolved by: https://github.com/OpenAPITools/openapi-generator-bazel/pull/25

**Comment by Sovietaced** [comment]
@mrmeku can this be closed?
