### ISSUE TITLE
Release v0.1.6 is missing asset for usage in WORKSPACE

### ISSUE THREAD

**Issue by bcspragu** [OpenAPITools/openapi-generator-bazel#44]
Hello there, and thanks for the project! I went to update to `0.1.6` and noticed there's no `
openapi-tools-generator-bazel-0.1.6.tar.gz ` to use in an `http_archive`. I don't know how that gets generated, but Bazel rejects the raw Source code archive with:

```
ERROR: Error computing the main repository mapping: Every .bzl file must have a corresponding package, but '@openapi_tools_generator_bazel//:defs.bzl' does not have one. Please create a BUILD file in the same or any parent directory. Note that this BUILD file does not need to do anything except exist.
```

Using something like this in the WORKSPACE:

```
http_archive(
    name = "openapi_tools_generator_bazel",
    sha256 = "cf22a0b9746a6246edc12079aa8d654deed578f54d6846c2fa26aae42ffe156a",
    urls = ["https://github.com/OpenAPITools/openapi-generator-bazel/archive/refs/tags/v0.1.6.tar.gz"],
)
```

**Comment by wing328** [comment]
I've added https://github.com/OpenAPITools/openapi-generator-bazel/releases/download/v0.1.6/openapi-tools-generator-bazel-0.1.6.tar.gz to the v0.1.6 release.

Can you please give it another try?

**Comment by bcspragu** [comment]
Works perfectly, thanks!
