### ISSUE TITLE
Example Usage Documentation

### ISSUE THREAD

**Issue by jonahgeorge** [OpenAPITools/openapi-generator-bazel#6]
Would it be possible to put an example of usage within a `go_library` target on the README? I've been having some trouble getting this to function (likely from lack of experience with Bazel). 

The following code always results in ["Unknown source type openapi"](https://github.com/bazelbuild/rules_go/blob/master/go/private/common.bzl#L110)

```
openapi_generator(
    name = "openapi",
    generator = "go-experimental",
    spec = "openapi.json",
)

go_library(
    name = "go_default_library",
    srcs = [":openapi"],
    importpath = "github.com/jonahgeorge/openapi-client",
    visibility = ["//visibility:public"],
)

go_binary(
    name = "exbin",
    srcs = ["main.go"],
    deps = [":go_default_library"],
    visibility = ["//visibility:public"],
)
```

**Comment by wing328** [comment]
@jonahgeorge sorry for late reply. We welcome PR to enhance the readme.

**Comment by nathanworms** [comment]
I am running into this same issue.  Any recommendations on how to actually use this rule to generate openapi model files which can be used as dependencies for a go_binary or a go_library?

I have found that a .go extension can be added to the target name, but that runs into other issues because non .go files are created too.

**Comment by tony-scio** [comment]
Same issue here, trying to figure out a `java_library` wasn't obvious to me. Did anyone else figure this out? I'd be happy to PR the example if so (or when I figure it out).

**Comment by Dogild** [comment]
Same issue here with `go_library`, did anyone else figure this out?

**Comment by loeffel-io** [comment]
+1
